apiVersion: v1
kind: Service
metadata:
    name: "schedulecluster-4cfe"
    labels:
        app: "schedulecluster-4cfe"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "schedulecluster-4cfe"