apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicinerepresentativeschedule
  labels:
    app: medicinerepresentativeschedule
spec:
  replicas: 1
  selector:
    matchLabels:
      service: medicinerepresentativeschedule
  template:
    metadata:
      labels:
        app: medicinerepresentativeschedule
        service: medicinerepresentativeschedule
    spec:
      containers:
        - name: medicinerepresentativeschedule
          image: mvccube.azurecr.io/schedule:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
      imagePullSecrets:
      - name: mvccube
---
apiVersion: v1
kind: Service
metadata:
  name: medicinerepresentativeschedule
  labels:
    app: medicinerepresentativeschedule
    service: medicinerepresentativeschedule
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: medicinerepresentativeschedule