on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: scheduleregistry.azurecr.io
        username: ${{ secrets.acr_scheduleregistry_username }}
        password: ${{ secrets.acr_scheduleregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/MedicineRepresentativeSchedule" -f  "MedicineRepresentativeSchedule/Dockerfile" -t scheduleregistry.azurecr.io/schedulecluster:${{ github.sha }} --label dockerfile-path=MedicineRepresentativeSchedule/Dockerfile
        docker push scheduleregistry.azurecr.io/schedulecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_schedulecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep schedulecluster2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace schedulecluster2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: schedulecluster2
        container-registry-url: scheduleregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_scheduleregistry_username }}
        container-registry-password: ${{ secrets.acr_scheduleregistry_password }}
        secret-name: scheduleclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: schedulecluster2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          scheduleregistry.azurecr.io/schedulecluster:${{ github.sha }}
        imagepullsecrets: |
          scheduleclusdockerauth
